---
# roles/docker/tasks/configure.yml
#
- name: docker security group
  ansible.builtin.user:
    append: yes
    groups:
      - docker
    name: "{{ item }}"
  with_items:
    - "{{ docker_group_members }}"

- name: configure remote access
  block:
    - name: /etc/systemd/system/docker.service.d
      ansible.builtin.file:
        group: root
        mode: 0755
        owner: root
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: systemd
      ansible.builtin.template:
        dest: /etc/systemd/system/docker.service.d/ExecStart.conf
        group: root
        lstrip_blocks: yes
        mode: 0644
        owner: root
        src: docker.service.j2
      notify:
        - systemctl daemon-reload
        - restart docker
  when:
    - docker_swarm_enabled

- name: tls
  block:
    - name: tls docker.ca
      ansible.builtin.copy:
        content: "{{ docker_tls_cacert }}"
        dest: "{{ docker_tls_cacert_path }}"
        mode: 0544

    - name: tls docker.cert
      ansible.builtin.copy:
        content: "{{ docker_tls_cert }}"
        dest: "{{ docker_tls_cert_path }}"
        mode: 0544

    - name: tls docker.key
      ansible.builtin.copy:
        content: "{{ docker_tls_key }}"
        dest: "{{ docker_tls_key_path }}"
        mode: 0544
  when:
    - docker_tls_cacert |length >0
    - docker_tls_cert |length >0
    - docker_tls_key |length >0

- name: daemon.json
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    lstrip_blocks: yes
    mode: 0644
    src: daemon.json.j2
  notify:
    - restart docker
