---
# roles/docker/tasks/configure-swarm.yml
# https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/
#
- name: swarm fact cluster managers
  ansible.builtin.set_fact:
    swarm_managers: |-
      [
      {%- set first = true -%}
      {%- for host in (ansible_play_hosts|sort) -%}
      {%- if hostvars[host]['ansible_local']['docker']['Swarm']['NodeID'] |length >0 %}
      {%- if not first %}, {% endif %}
      "{{ host }}"
      {%- set first = false %}
      {%- endif %}
      {%- endfor -%}
      ]

- name: swarm fact primary host
  ansible.builtin.set_fact:
    swarm_manager_primary: "{{(swarm_managers|first) |default(ansible_play_hosts|sort|first)}}"

- name: swarm facts
  ansible.builtin.set_fact:
    advertise_addr: "{{hostvars[swarm_manager_primary]['ansible_default_ipv4']['address']}}"

- name: swarm init
  ansible.builtin.shell:
    cmd: >
      docker swarm init
      --advertise-addr {{docker_swarm_advertise_addr |default(advertise_addr)}}:{{docker_swarm_port}}
      --listen-addr {{docker_swarm_listen_addr |default(advertise_addr)}}:{{docker_swarm_port}}
  when:
    - inventory_hostname == swarm_manager_primary
  notify:
    - update local facts

- name: swarm join
  block:
    - name: get manager join token
      ansible.builtin.shell:
        cmd: /usr/bin/docker swarm join-token manager |sed -n '/docker swarm join --token/p' |xargs
      register: docker_swarm_join
      delegate_to: "{{swarm_manager_primary}}"

    - name: swarm join
      ansible.builtin.command:
        cmd: "{{ docker_swarm_join.stdout }}"
      notify:
        - update local facts
  when:
    - not inventory_hostname == swarm_manager_primary
