---
# tasks file for docker
- name: Docker prereq.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Docker gpg import
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_id }}"
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Docker repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Docker install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce={{ docker_version }}
    - docker-ce-cli={{ docker_version }}
    - containerd.io={{ containerd_version }}

- name: Docker group
  ansible.builtin.user:
    append: yes
    groups:
      - docker
    name: "{{ item }}"
  with_items:
    - "{{ docker_group_members }}"

- name: Ansible fact.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
- name: Docker fact
  ansible.builtin.copy:
    content: |
      #!/usr/bin/env sh
      /usr/bin/docker info --format "{{'{{'}} json . {{'}}'}}"
    dest: /etc/ansible/facts.d/docker.fact
    mode: 0755
  register: docker_fact
- name: Re-read facts
  ansible.builtin.setup:
    filter: ansible_local
  when: docker_fact.changed
