---
# tasks file for docker
- name: prerequisite
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: gpg import
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_id }}"
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: security group
  ansible.builtin.user:
    append: yes
    groups:
      - docker
    name: "{{ item }}"
  with_items:
    - "{{ docker_group_members }}"

- name: fact.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory

- name: fact
  ansible.builtin.template:
    dest: /etc/ansible/facts.d/docker.fact
    group: root
    lstrip_blocks: yes
    mode: 0755
    owner: root
    src: docker.fact.j2
  register: docker_fact

- name: re-read facts
  ansible.builtin.setup:
    filter: ansible_local
  when: docker_fact.changed
