---
# roles/docker/tasks/intall-Ubuntu.yml
#
- name: prerequisite
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: gpg import
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_id }}"
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: >
      deb [arch={{(ansible_machine =='x86_64') |ternary('amd64',ansible_machine)}}]
      https://download.docker.com/linux/ubuntu
      {{ansible_distribution_release}}
      stable
    state: present
    update_cache: yes

- name: install
  ansible.builtin.apt:
    cache_valid_time: 86400
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
