---
# roles/docker/tasks/main.yml
#
- name: setup facts
  ansible.builtin.include_tasks: configure-facts.yml

- name: install
  ansible.builtin.include_tasks: install-{{ansible_distribution}}.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: swarm configuration
  ansible.builtin.include_tasks: configure-swarm.yml
  when:
    - docker_swarm_enabled
    - ansible_local.docker.Swarm.NodeID |length ==0
