---
# tasks file for docker
- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags: configure
  tags: configure

- name: swarm
  block:
    - name: docker swarm managers?
      ansible.builtin.set_fact:
        docker_swarm_managers: "{{ (groups[docker_swarm_group] | default(ansible_play_hosts)) | intersect(ansible_play_hosts_all) }}"
    - ansible.builtin.debug:
        msg: Docker swarm manager nodes are {{ docker_swarm_managers }}

    - name: swarm init
      include_tasks: swarm-init.yml
      when:
        - inventory_hostname == docker_swarm_managers |first

    - name: docker swarm manager address?
      ansible.builtin.set_fact:
        docker_swarm_manager_addr: "{{ hostvars[(docker_swarm_managers |first)]['ansible_local']['docker']['Swarm']['NodeAddr'] }}"
      when:
        - inventory_hostname != docker_swarm_managers |first

    - name: swarm join manager
      include_tasks: swarm-join-manager.yml
      when:
        - inventory_hostname in docker_swarm_managers
        - inventory_hostname != docker_swarm_managers |first

    - name: swarm join worker
      include_tasks: swarm-join-worker.yml
      when:
        - inventory_hostname not in docker_swarm_managers

  tags: [docker_swarm]
  when:
    - docker_swarm |bool
    - ansible_local.docker is defined
    - ansible_local.docker.Swarm is defined
    - ansible_local.docker.Swarm.NodeID | length == 0
