---
# tasks file for docker swarm join manager
- name: Register swarm join token manager
  ansible.builtin.shell:
    cmd: docker swarm join-token -q manager
  changed_when: false
  delegate_facts: true
  delegate_to: "{{ docker_swarm_managers |first }}"
  register: docker_swarm_join_token_manager

- name: Docker swarm join manager
  ansible.builtin.command:
    cmd: >
      docker swarm join
      --advertise-addr {{ docker_swarm_advertise_addr }}:{{ docker_swarm_port }}
      --listen-addr {{ docker_swarm_listen_addr }}:{{ docker_swarm_port }}
      --token {{ docker_swarm_join_token_manager.stdout }}
      {{ docker_swarm_manager_addr }}:{{ docker_swarm_port }}
