---
# https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/
- name: Docker swarm init
  ansible.builtin.command:
    cmd: >
      docker swarm init
      --advertise-addr {{ docker_swarm_advertise_addr }}:{{ docker_swarm_port }}
      --listen-addr {{ docker_swarm_listen_addr }}:{{ docker_swarm_port }}
