---
# task file for docker swarm join worker
- name: Register swarm join token worker
  ansible.builtin.shell:
    cmd: docker swarm join-token -q worker
  changed_when: false
  delegate_facts: true
  delegate_to: "{{ docker_swarm_managers |first }}"
  register: docker_swarm_join_token_worker

- name: Docker swarm join worker
  ansible.builtin.command:
    cmd: >
      docker swarm join
      --advertise-addr {{ docker_swarm_advertise_addr }}:{{ docker_swarm_port }}
      --listen-addr {{ docker_swarm_listen_addr }}:{{ docker_swarm_port }}
      --token {{ docker_swarm_join_token_worker.stdout }}
      {{ docker_swarm_manager_addr }}:{{ docker_swarm_port }}
