---
# tasks file for docker swarm join manager
- name: Register swarm join token manager
  ansible.builtin.shell:
    cmd: docker swarm join-token -q manager
  changed_when: false
  delegate_facts: true
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  register: swarm_join_token_manager

- name: Docker swarm join manager
  ansible.builtin.command:
    cmd: >
      docker swarm join
      --advertise-addr {{ swarm.advertise_addr }}:{{ swarm.port }}
      --listen-addr {{ swarm.listen_addr }}:{{ swarm.port }}
      --token {{ swarm_join_token_manager.stdout }}
      {{ swarm_manager_addr }}:{{ swarm.port }}
